# Generated by Django 4.1.1 on 2022-09-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
