# Generated by Django 4.1.1 on 2022-09-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_userprofile_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
